name: build_and_test

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

  # Whenever certain branches are pushed
  push:
    branches: [main]

  # On demand from github.com for testing
  workflow_dispatch:

# Ensures that only one workflow runs at a time for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ubuntu_build_and_test:
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [22.04, 24.04]

    runs-on: self-hosted  #ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/ubuntu/Dockerfile
          tags: roboplan_ubuntu:${{ github.head_ref || github.ref_name }}
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          push: false
          load: true
      - name: Run tests
        run: |
          docker run --rm \
            roboplan_ubuntu:${{ github.head_ref || github.ref_name }} \
            /bin/bash -c './scripts/run_tests.bash'
      # Always remove images to save disk space, may not be necessary when using GH runners.
      - name: Clean up Docker image
        if: always()
        run: docker rmi roboplan_ubuntu:${{ github.head_ref || github.ref_name }} || true

  # Build ROS docker images and run tests.
  ros_build_and_test:
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy, kilted, rolling]

    runs-on: self-hosted  #ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/ros/Dockerfile
          tags: roboplan_ros:${{ github.head_ref || github.ref_name }}
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
          push: false
          load: true
      - name: Run tests
        run: |
          docker run --rm \
            roboplan_ros:${{ github.head_ref || github.ref_name }} \
            /bin/bash -c './src/roboplan/scripts/run_tests.bash'
      # Always remove images to save disk space, may not be necessary when using GH runners.
      - name: Clean up Docker image
        if: always()
        run: docker rmi roboplan_ros:${{ github.head_ref || github.ref_name }} || true

  pixi_build_and_test:
    env:
      SCCACHE_DIR: ${{ github.workspace }}/.sccache
    strategy:
      fail-fast: false
      # TODO: Re-enable when we do not have self-hosted runners in the public repo
      # matrix:
      #   ubuntu_version: [22.04, 24.04]

    runs-on: self-hosted  #ubuntu-${{ matrix.ubuntu_version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # Cache build directories and sccache
      - name: Cache build directories and sccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.SCCACHE_DIR }}
          key: ${{ runner.os }}-build-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build
      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          manifest-path: pixi.toml
          # TODO: Remove this when we do not have self-hosted runners in the public repo
          pixi-bin-path: ~/actions-runner/.pixi/bin/pixi
      - name: Build and test
        run: |
          pixi run install_all
          pixi run build_tests
          pixi run test_all
      # TODO: Decide on a method for automated benchmark performance testing.
      - name: Run benchmarks
        run: |
          pixi run test_benchmarks
